version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build:
      context: ./frontend  # Reactのプロジェクトディレクトリ
      dockerfile: Dockerfile  # React専用のDockerfile（フロントエンド用）
    command: npm start  # React開発サーバーを起動
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
